class_name RimFire
extends Node3D
## "On fire" rim: a single line of flames burning along the top of the ring
## while the shooter is on a streak, puffs of smoke when it goes out, and the
## steel glowing. Both effects are authored in Blender as flipbooks
## (tools/blender/render_fire_flipbook.py → assets/textures/fx_fire_sheet.png,
## render_smoke_flipbook.py → fx_smoke_sheet.png): the flames wrap a thin
## ribbon standing on the ring (game/court/fire_ribbon.gdshader); the smoke is
## a handful of camera-facing puffs around the ring (smoke_puff.gdshader) that
## each play the sheet once. Parented under the rim pivot so it rides wobbles
## and the miss clip. Presentation only.

const SHEET_TEX := "res://assets/textures/fx_fire_sheet.png"
const SMOKE_TEX := "res://assets/textures/fx_smoke_sheet.png"
## The old single soft blob (still generated by gen_fx_textures.lua) — a handy sprite for specks.
const SMOKE_TEX_SOFT := "res://assets/textures/fx_smoke.png"
const RING_R := SimConstants.R_RIM
const RIBBON_R := SimConstants.R_RIM + 0.006
const RIBBON_H := 0.07
const SEGMENTS := 48
const PUFFS := 6
const PUFF_SIZE := 0.38
const PUFF_DURATION := 1.5
const PUFF_STAGGER := 0.12   # each puff starts a little after the last
const FADE_IN := 6.0
const FADE_OUT := 4.0

var _flames: MeshInstance3D
var _flame_mat: ShaderMaterial
var _smoke: Node3D
var _puff_mats: Array[ShaderMaterial] = []
var _smoke_start := -10.0
var _light: OmniLight3D
var _rim_mat: StandardMaterial3D
var _lit := false
var _intensity := 0.0
var _intensity_target := 0.0
var _light_target := 0.0
var _glow_target := 0.0
var _t := 0.0


func _ready() -> void:
	_flames = MeshInstance3D.new()
	_flames.name = "Flames"
	_flames.mesh = _ribbon_mesh()
	_flame_mat = ShaderMaterial.new()
	_flame_mat.shader = load("res://game/court/fire_ribbon.gdshader")
	_flame_mat.set_shader_parameter("sheet", load(SHEET_TEX))
	_flame_mat.set_shader_parameter("intensity", 0.0)
	_flames.material_override = _flame_mat
	_flames.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	_flames.visible = false
	add_child(_flames)

	var puffs := build_puffs("Smoke", PUFF_SIZE, Color.WHITE)
	_smoke = puffs[0]
	_puff_mats = puffs[1]
	add_child(_smoke)

	_light = OmniLight3D.new()
	_light.name = "Glow"
	_light.light_color = Color(1.0, 0.55, 0.2)
	_light.light_energy = 0.0
	_light.omni_range = 1.2
	_light.position = Vector3(0.0, 0.15, 0.0)
	add_child(_light)


## Give the effect the rim mesh so it can make the steel glow. Optional.
func setup(rim: MeshInstance3D) -> void:
	if rim == null or rim.mesh == null or rim.mesh.get_surface_count() == 0:
		return
	var src := rim.mesh.surface_get_material(0)
	if src is StandardMaterial3D:
		_rim_mat = (src as StandardMaterial3D).duplicate()
		_rim_mat.emission_enabled = true
		_rim_mat.emission = Color(1.0, 0.35, 0.08)
		_rim_mat.emission_energy_multiplier = 0.0
		rim.material_override = _rim_mat


func is_lit() -> bool:
	return _lit


## Current flame strength 0..1.2 (the shader fades and stretches with it).
func intensity() -> float:
	return _intensity


## Light it (or turn it up): level = the streak length (StreakRules.FIRE_AT =
## just lit; full blaze from the top tier at 11).
func ignite(level: int) -> void:
	var k := clampf(float(level - StreakRules.FIRE_AT) / 6.0, 0.0, 1.0)
	if not _lit:
		_flames.visible = true
		_smoke.visible = false
		_smoke_start = -10.0
		Sfx.fire_burst()
	_lit = true
	_intensity_target = lerpf(0.75, 1.2, k)
	_light_target = lerpf(0.3, 0.5, k)
	_glow_target = lerpf(0.6, 1.0, k)


## Out: the flames die down, a puff of smoke, the steel cools.
func extinguish() -> void:
	if not _lit:
		return
	_lit = false
	_intensity_target = 0.0
	_smoke_start = _t
	_smoke.visible = true
	_light_target = 0.0
	_glow_target = 0.0
	Sfx.fire_out()


func _process(dt: float) -> void:
	if _light == null or _flames == null or _smoke == null:
		return  # not built (shouldn't happen) — never spam the log
	_t += dt
	var rate := FADE_IN if _lit else FADE_OUT
	_intensity = lerpf(_intensity, _intensity_target, minf(1.0, rate * dt))
	if not _lit and _intensity < 0.02:
		_intensity = 0.0
		_flames.visible = false
	_flame_mat.set_shader_parameter("t", _t)
	_flame_mat.set_shader_parameter("intensity", _intensity)
	_light.light_energy = lerpf(_light.light_energy, _light_target, minf(1.0, rate * dt))
	# The light flickers a touch while lit.
	if _lit:
		_light.light_energy *= 0.9 + 0.1 * sin(_t * 23.0) * sin(_t * 7.3)
	if _rim_mat != null:
		_rim_mat.emission_energy_multiplier = lerpf(_rim_mat.emission_energy_multiplier, _glow_target, minf(1.0, rate * dt))
	if _smoke.visible:
		var age := _t - _smoke_start
		for i in _puff_mats.size():
			_puff_mats[i].set_shader_parameter("age", age - float(i) * PUFF_STAGGER)
		if age > PUFF_DURATION + float(PUFFS) * PUFF_STAGGER:
			_smoke.visible = false   # every puff has played out


## An open cylinder strip standing on the ring: u runs around (0..1), v is 0 at
## the top and 1 at the base (the sheet's frames are stored top-down).
static func _ribbon_mesh() -> ArrayMesh:
	var verts := PackedVector3Array()
	var uvs := PackedVector2Array()
	var normals := PackedVector3Array()
	var idx := PackedInt32Array()
	for i in SEGMENTS + 1:
		var a := TAU * float(i) / float(SEGMENTS)
		var u := float(i) / float(SEGMENTS)
		var dir := Vector3(cos(a), 0.0, sin(a))
		verts.append(dir * RIBBON_R)
		uvs.append(Vector2(u, 1.0))
		normals.append(dir)
		verts.append(dir * RIBBON_R + Vector3(0.0, RIBBON_H, 0.0))
		uvs.append(Vector2(u, 0.0))
		normals.append(dir)
	for i in SEGMENTS:
		var b := i * 2
		idx.append_array(PackedInt32Array([b, b + 2, b + 1, b + 1, b + 2, b + 3]))
	var arrays := []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_INDEX] = idx
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


## Camera-facing quads spaced around the ring, each with its own material so
## the puffs can start one after another and mirror alternately. Shared with
## RimIce (a tinted mist). Returns [root: Node3D, mats: Array[ShaderMaterial]].
static func build_puffs(name_: String, size: float, tint: Color) -> Array:
	var root := Node3D.new()
	root.name = name_
	root.visible = false
	var mats: Array[ShaderMaterial] = []
	var shader: Shader = load("res://game/court/smoke_puff.gdshader")
	var sheet: Texture2D = load(SMOKE_TEX)
	var quad := QuadMesh.new()
	quad.size = Vector2(size, size)
	quad.center_offset = Vector3(0.0, size * 0.35, 0.0)
	for i in PUFFS:
		var a := TAU * (float(i) + 0.5) / float(PUFFS)
		var mi := MeshInstance3D.new()
		mi.name = "Puff%d" % i
		mi.mesh = quad
		mi.position = Vector3(cos(a), 0.0, sin(a)) * (RING_R - 0.02)
		var mat := ShaderMaterial.new()
		mat.shader = shader
		mat.set_shader_parameter("sheet", sheet)
		mat.set_shader_parameter("duration", PUFF_DURATION)
		mat.set_shader_parameter("flip", -1.0 if i % 2 == 1 else 1.0)
		mat.set_shader_parameter("age", -1.0)
		mat.set_shader_parameter("tint", tint)
		mi.material_override = mat
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		mats.append(mat)
	return [root, mats]
